// 100 flight achievements grouped by theme.
// Each achievement has: id, category, icon (lucide name), tier (bronze/silver/gold/platinum),
// title + description per language, and a `check(ctx)` function that returns true/false.

const tier = {
  BRONZE: "bronze",
  SILVER: "silver",
  GOLD: "gold",
  PLATINUM: "platinum",
};

const c = (ctx) => ctx || {};

export const ACHIEVEMENTS = [
  // --- Landing Precision (1-10) ---
  { id: "soft_touch_1", category: "landing", tier: tier.BRONZE, icon: "Feather",
    en: { title: "Soft Touch", desc: "Land with less than 150 fpm vertical speed." },
    de: { title: "Sanfte Berührung", desc: "Landung mit weniger als 150 fpm Sinkrate." },
    check: (ctx) => (c(ctx).softLandings || 0) >= 1 },
  { id: "butter_landing", category: "landing", tier: tier.SILVER, icon: "Sparkles",
    en: { title: "Butter Landing", desc: "Achieve one landing under 100 fpm." },
    de: { title: "Butter-Landung", desc: "Eine Landung unter 100 fpm erreichen." },
    check: (ctx) => (c(ctx).butterLandings || 0) >= 1 },
  { id: "butter_master", category: "landing", tier: tier.GOLD, icon: "Sparkles",
    en: { title: "Butter Master", desc: "10 butter landings." },
    de: { title: "Butter-Meister", desc: "10 butterweiche Landungen." },
    check: (ctx) => (c(ctx).butterLandings || 0) >= 10 },
  { id: "butter_legend", category: "landing", tier: tier.PLATINUM, icon: "Award",
    en: { title: "Butter Legend", desc: "50 butter landings." },
    de: { title: "Butter-Legende", desc: "50 butterweiche Landungen." },
    check: (ctx) => (c(ctx).butterLandings || 0) >= 50 },
  { id: "gentle_giant", category: "landing", tier: tier.SILVER, icon: "Cloud",
    en: { title: "Gentle Giant", desc: "Soft landing in a wide-body." },
    de: { title: "Sanfter Riese", desc: "Weiche Landung mit einem Widebody." },
    check: (ctx) => ctx.flights.some(f => (f.xplane_data?.touchdown_vspeed && Math.abs(f.xplane_data.touchdown_vspeed) < 150) && ["wide_body","cargo"].includes(ctx.aircraftTypeOfFlight?.(f))) },
  { id: "precision_g", category: "landing", tier: tier.SILVER, icon: "Target",
    en: { title: "Low-G Touchdown", desc: "Landing G-load under 1.2g." },
    de: { title: "Low-G Aufsetzen", desc: "Lande-G unter 1,2g." },
    check: (ctx) => ctx.flights.some(f => (f.landing_g_force || f.xplane_data?.landing_g_force) && (f.landing_g_force || f.xplane_data?.landing_g_force) < 1.2) },
  { id: "ten_softs", category: "landing", tier: tier.BRONZE, icon: "CloudRain",
    en: { title: "Consistent Hands", desc: "10 soft landings (<150 fpm)." },
    de: { title: "Sichere Hände", desc: "10 weiche Landungen (<150 fpm)." },
    check: (ctx) => (c(ctx).softLandings || 0) >= 10 },
  { id: "hundred_softs", category: "landing", tier: tier.GOLD, icon: "ShieldCheck",
    en: { title: "Cushioned Career", desc: "100 soft landings." },
    de: { title: "Weiche Karriere", desc: "100 weiche Landungen." },
    check: (ctx) => (c(ctx).softLandings || 0) >= 100 },
  { id: "no_hard_streak", category: "landing", tier: tier.SILVER, icon: "Shield",
    en: { title: "No-Bang Streak", desc: "25 flights without a hard landing." },
    de: { title: "Keine harten Landungen", desc: "25 Flüge ohne harte Landung in Folge." },
    check: (ctx) => (c(ctx).longestNoHardStreak || 0) >= 25 },
  { id: "greaser_row", category: "landing", tier: tier.GOLD, icon: "Trophy",
    en: { title: "Greaser Row", desc: "5 butter landings in a row." },
    de: { title: "Butter-Serie", desc: "5 Butter-Landungen in Folge." },
    check: (ctx) => (c(ctx).longestButterStreak || 0) >= 5 },

  // --- Centerline / Precision (11-20) ---
  { id: "centerline_rookie", category: "precision", tier: tier.BRONZE, icon: "Minus",
    en: { title: "On The Line", desc: "Landing centerline deviation under 5 m." },
    de: { title: "Auf der Linie", desc: "Landebahn-Abweichung unter 5 m." },
    check: (ctx) => (c(ctx).perfectCenterlineLandings || 0) >= 1 },
  { id: "precision_master", category: "precision", tier: tier.GOLD, icon: "Crosshair",
    en: { title: "Precision Master", desc: "10 landings with <2 m centerline deviation." },
    de: { title: "Präzisions-Meister", desc: "10 Landungen mit <2 m Abweichung zur Mittellinie." },
    check: (ctx) => (c(ctx).excellentCenterlineLandings || 0) >= 10 },
  { id: "laser_takeoff", category: "precision", tier: tier.SILVER, icon: "Rocket",
    en: { title: "Laser Takeoff", desc: "Takeoff roll with <2 m centerline deviation." },
    de: { title: "Laser-Start", desc: "Startlauf mit <2 m Abweichung zur Mittellinie." },
    check: (ctx) => (c(ctx).excellentCenterlineTakeoffs || 0) >= 1 },
  { id: "track_hero", category: "precision", tier: tier.GOLD, icon: "Route",
    en: { title: "Tracking Hero", desc: "10 takeoffs with <2 m centerline deviation." },
    de: { title: "Tracking-Held", desc: "10 Starts mit <2 m Abweichung." },
    check: (ctx) => (c(ctx).excellentCenterlineTakeoffs || 0) >= 10 },
  { id: "pin_drop", category: "precision", tier: tier.GOLD, icon: "MapPin",
    en: { title: "Pin Drop Landing", desc: "Land within touchdown zone markers." },
    de: { title: "Punktlandung", desc: "Aufsetzen innerhalb TDZ-Bereich." },
    check: (ctx) => (c(ctx).tdzLandings || 0) >= 1 },
  { id: "tdz_pro", category: "precision", tier: tier.PLATINUM, icon: "Award",
    en: { title: "TDZ Pro", desc: "25 landings in the touchdown zone." },
    de: { title: "TDZ-Profi", desc: "25 Landungen in der Aufsetzzone." },
    check: (ctx) => (c(ctx).tdzLandings || 0) >= 25 },
  { id: "both_perfect", category: "precision", tier: tier.PLATINUM, icon: "Sparkles",
    en: { title: "Perfect Both Ends", desc: "Takeoff AND landing <2 m on same flight." },
    de: { title: "Beide perfekt", desc: "Start UND Landung mit <2 m auf demselben Flug." },
    check: (ctx) => (c(ctx).perfectBothEndsCount || 0) >= 1 },
  { id: "precision_100", category: "precision", tier: tier.PLATINUM, icon: "Trophy",
    en: { title: "Centerline Centurion", desc: "100 precise centerline landings (<5 m)." },
    de: { title: "Mittellinien-Legende", desc: "100 präzise Mittellinien-Landungen (<5 m)." },
    check: (ctx) => (c(ctx).perfectCenterlineLandings || 0) >= 100 },
  { id: "stable_approach", category: "precision", tier: tier.SILVER, icon: "TrendingDown",
    en: { title: "Stable Approach", desc: "Land with score 90+ on a 300+ NM flight." },
    de: { title: "Stabiler Anflug", desc: "Landung mit Score 90+ auf einem 300+ NM Flug." },
    check: (ctx) => ctx.flights.some(f => (f.flight_score || f.xplane_data?.final_score || 0) >= 90 && (f.xplane_data?.contract_distance_nm || 0) >= 300) },
  { id: "steady_hand", category: "precision", tier: tier.GOLD, icon: "Activity",
    en: { title: "Steady Hand", desc: "Max G under 1.4 on an entire flight." },
    de: { title: "Ruhige Hand", desc: "Max-G unter 1,4 über einen ganzen Flug." },
    check: (ctx) => ctx.flights.some(f => (f.max_g_force || 0) > 0 && (f.max_g_force || 0) < 1.4) },

  // --- Score tiers (21-30) ---
  { id: "score_80", category: "score", tier: tier.BRONZE, icon: "Star",
    en: { title: "Good Flight", desc: "Score 80+ on any flight." },
    de: { title: "Guter Flug", desc: "Score 80+ bei einem Flug." },
    check: (ctx) => (c(ctx).bestScore || 0) >= 80 },
  { id: "score_90", category: "score", tier: tier.SILVER, icon: "Star",
    en: { title: "Great Flight", desc: "Score 90+ on any flight." },
    de: { title: "Starker Flug", desc: "Score 90+ bei einem Flug." },
    check: (ctx) => (c(ctx).bestScore || 0) >= 90 },
  { id: "score_95", category: "score", tier: tier.GOLD, icon: "Medal",
    en: { title: "Elite Flight", desc: "Score 95+ on any flight." },
    de: { title: "Elite-Flug", desc: "Score 95+ bei einem Flug." },
    check: (ctx) => (c(ctx).bestScore || 0) >= 95 },
  { id: "score_99", category: "score", tier: tier.PLATINUM, icon: "Crown",
    en: { title: "Near Perfect", desc: "Score 99+ on any flight." },
    de: { title: "Beinahe Perfekt", desc: "Score 99+ bei einem Flug." },
    check: (ctx) => (c(ctx).bestScore || 0) >= 99 },
  { id: "avg_85", category: "score", tier: tier.SILVER, icon: "TrendingUp",
    en: { title: "Consistent Pro", desc: "Average score of 85+ (min 10 flights)." },
    de: { title: "Konstant gut", desc: "Durchschnitts-Score 85+ (mind. 10 Flüge)." },
    check: (ctx) => (c(ctx).completedFlights || 0) >= 10 && (c(ctx).avgScore || 0) >= 85 },
  { id: "avg_90", category: "score", tier: tier.GOLD, icon: "BarChart3",
    en: { title: "Top Performer", desc: "Average score 90+ (min 25 flights)." },
    de: { title: "Top-Performer", desc: "Durchschnitts-Score 90+ (mind. 25 Flüge)." },
    check: (ctx) => (c(ctx).completedFlights || 0) >= 25 && (c(ctx).avgScore || 0) >= 90 },
  { id: "ten_perfects", category: "score", tier: tier.GOLD, icon: "Star",
    en: { title: "Perfectionist", desc: "10 flights with score 99+." },
    de: { title: "Perfektionist", desc: "10 Flüge mit Score 99+." },
    check: (ctx) => (c(ctx).perfectScoreCount || 0) >= 10 },
  { id: "fifty_perfects", category: "score", tier: tier.PLATINUM, icon: "Crown",
    en: { title: "Perfection Tycoon", desc: "50 flights with score 99+." },
    de: { title: "Perfektions-Tycoon", desc: "50 Flüge mit Score 99+." },
    check: (ctx) => (c(ctx).perfectScoreCount || 0) >= 50 },
  { id: "score_streak_10", category: "score", tier: tier.SILVER, icon: "Zap",
    en: { title: "Hot Streak", desc: "10 flights in a row with score 90+." },
    de: { title: "Heiße Serie", desc: "10 Flüge hintereinander mit Score 90+." },
    check: (ctx) => (c(ctx).bestHighScoreStreak || 0) >= 10 },
  { id: "score_streak_25", category: "score", tier: tier.PLATINUM, icon: "Flame",
    en: { title: "Unstoppable", desc: "25 flights in a row with score 90+." },
    de: { title: "Unaufhaltsam", desc: "25 Flüge hintereinander mit Score 90+." },
    check: (ctx) => (c(ctx).bestHighScoreStreak || 0) >= 25 },

  // --- Flight milestones (31-40) ---
  { id: "first_flight", category: "milestone", tier: tier.BRONZE, icon: "Plane",
    en: { title: "First Flight", desc: "Complete your first flight." },
    de: { title: "Erster Flug", desc: "Ersten Flug abschließen." },
    check: (ctx) => (c(ctx).completedFlights || 0) >= 1 },
  { id: "flights_10", category: "milestone", tier: tier.BRONZE, icon: "Plane",
    en: { title: "Rookie Pilot", desc: "Complete 10 flights." },
    de: { title: "Anfänger-Pilot", desc: "10 Flüge abschließen." },
    check: (ctx) => (c(ctx).completedFlights || 0) >= 10 },
  { id: "flights_50", category: "milestone", tier: tier.SILVER, icon: "Plane",
    en: { title: "Regular Aviator", desc: "Complete 50 flights." },
    de: { title: "Routinierter Flieger", desc: "50 Flüge abschließen." },
    check: (ctx) => (c(ctx).completedFlights || 0) >= 50 },
  { id: "flights_100", category: "milestone", tier: tier.SILVER, icon: "Plane",
    en: { title: "Century Pilot", desc: "Complete 100 flights." },
    de: { title: "Hundert-Flüge-Pilot", desc: "100 Flüge abschließen." },
    check: (ctx) => (c(ctx).completedFlights || 0) >= 100 },
  { id: "flights_250", category: "milestone", tier: tier.GOLD, icon: "Plane",
    en: { title: "Seasoned Captain", desc: "Complete 250 flights." },
    de: { title: "Erfahrener Kapitän", desc: "250 Flüge abschließen." },
    check: (ctx) => (c(ctx).completedFlights || 0) >= 250 },
  { id: "flights_500", category: "milestone", tier: tier.GOLD, icon: "Plane",
    en: { title: "Flight Master", desc: "Complete 500 flights." },
    de: { title: "Flug-Meister", desc: "500 Flüge abschließen." },
    check: (ctx) => (c(ctx).completedFlights || 0) >= 500 },
  { id: "flights_1000", category: "milestone", tier: tier.PLATINUM, icon: "Trophy",
    en: { title: "Legendary Aviator", desc: "Complete 1000 flights." },
    de: { title: "Legendärer Flieger", desc: "1000 Flüge abschließen." },
    check: (ctx) => (c(ctx).completedFlights || 0) >= 1000 },
  { id: "hours_50", category: "milestone", tier: tier.BRONZE, icon: "Clock",
    en: { title: "50 Hour Club", desc: "Log 50 flight hours." },
    de: { title: "50-Stunden-Club", desc: "50 Flugstunden sammeln." },
    check: (ctx) => (c(ctx).totalHours || 0) >= 50 },
  { id: "hours_500", category: "milestone", tier: tier.GOLD, icon: "Clock",
    en: { title: "500 Hour Pilot", desc: "Log 500 flight hours." },
    de: { title: "500-Stunden-Pilot", desc: "500 Flugstunden sammeln." },
    check: (ctx) => (c(ctx).totalHours || 0) >= 500 },
  { id: "hours_2000", category: "milestone", tier: tier.PLATINUM, icon: "Clock",
    en: { title: "ATPL Territory", desc: "Log 2000 flight hours." },
    de: { title: "ATPL-Bereich", desc: "2000 Flugstunden sammeln." },
    check: (ctx) => (c(ctx).totalHours || 0) >= 2000 },

  // --- Distance (41-48) ---
  { id: "distance_1000", category: "distance", tier: tier.BRONZE, icon: "Map",
    en: { title: "Short-Haul Cadet", desc: "Fly 1,000 NM total." },
    de: { title: "Kurzstrecken-Kadett", desc: "1.000 NM geflogen." },
    check: (ctx) => (c(ctx).totalDistanceNm || 0) >= 1000 },
  { id: "distance_10k", category: "distance", tier: tier.SILVER, icon: "Map",
    en: { title: "Continental", desc: "Fly 10,000 NM total." },
    de: { title: "Kontinentalpilot", desc: "10.000 NM geflogen." },
    check: (ctx) => (c(ctx).totalDistanceNm || 0) >= 10000 },
  { id: "distance_50k", category: "distance", tier: tier.GOLD, icon: "Globe",
    en: { title: "Global Flyer", desc: "Fly 50,000 NM total." },
    de: { title: "Weltenbummler", desc: "50.000 NM geflogen." },
    check: (ctx) => (c(ctx).totalDistanceNm || 0) >= 50000 },
  { id: "distance_100k", category: "distance", tier: tier.PLATINUM, icon: "Globe",
    en: { title: "Around the World", desc: "Fly 100,000 NM total." },
    de: { title: "Um die Welt", desc: "100.000 NM geflogen." },
    check: (ctx) => (c(ctx).totalDistanceNm || 0) >= 100000 },
  { id: "long_haul_1", category: "distance", tier: tier.SILVER, icon: "PlaneTakeoff",
    en: { title: "Long Hauler", desc: "Complete a flight over 2000 NM." },
    de: { title: "Langstrecken-Pilot", desc: "Flug über 2.000 NM abschließen." },
    check: (ctx) => (c(ctx).longestFlightDistanceNm || 0) >= 2000 },
  { id: "long_haul_2", category: "distance", tier: tier.GOLD, icon: "PlaneTakeoff",
    en: { title: "Ocean Crosser", desc: "Complete a flight over 4000 NM." },
    de: { title: "Ozeanüberquerer", desc: "Flug über 4.000 NM abschließen." },
    check: (ctx) => (c(ctx).longestFlightDistanceNm || 0) >= 4000 },
  { id: "long_haul_3", category: "distance", tier: tier.PLATINUM, icon: "Globe",
    en: { title: "Ultra Long Haul", desc: "Complete a flight over 6000 NM." },
    de: { title: "Ultra-Langstrecke", desc: "Flug über 6.000 NM abschließen." },
    check: (ctx) => (c(ctx).longestFlightDistanceNm || 0) >= 6000 },
  { id: "marathon", category: "distance", tier: tier.GOLD, icon: "Timer",
    en: { title: "Marathon", desc: "Single flight over 10 hours." },
    de: { title: "Marathon", desc: "Einzelflug über 10 Stunden." },
    check: (ctx) => (c(ctx).longestFlightHours || 0) >= 10 },

  // --- Passengers / Cargo (49-56) ---
  { id: "pax_100", category: "passengers", tier: tier.BRONZE, icon: "Users",
    en: { title: "First 100 Pax", desc: "Carry 100 passengers total." },
    de: { title: "Erste 100 Pax", desc: "100 Passagiere befördert." },
    check: (ctx) => (c(ctx).totalPassengers || 0) >= 100 },
  { id: "pax_1k", category: "passengers", tier: tier.SILVER, icon: "Users",
    en: { title: "Thousand Souls", desc: "Carry 1,000 passengers." },
    de: { title: "Tausend Seelen", desc: "1.000 Passagiere befördert." },
    check: (ctx) => (c(ctx).totalPassengers || 0) >= 1000 },
  { id: "pax_10k", category: "passengers", tier: tier.GOLD, icon: "Users",
    en: { title: "People Mover", desc: "Carry 10,000 passengers." },
    de: { title: "Menschen-Transport", desc: "10.000 Passagiere befördert." },
    check: (ctx) => (c(ctx).totalPassengers || 0) >= 10000 },
  { id: "pax_100k", category: "passengers", tier: tier.PLATINUM, icon: "Users",
    en: { title: "Airline Tycoon", desc: "Carry 100,000 passengers." },
    de: { title: "Airline-Tycoon", desc: "100.000 Passagiere befördert." },
    check: (ctx) => (c(ctx).totalPassengers || 0) >= 100000 },
  { id: "cargo_10t", category: "cargo", tier: tier.BRONZE, icon: "Package",
    en: { title: "Cargo Rookie", desc: "Haul 10 tonnes of cargo." },
    de: { title: "Fracht-Anfänger", desc: "10 Tonnen Fracht befördert." },
    check: (ctx) => (c(ctx).totalCargoKg || 0) >= 10000 },
  { id: "cargo_100t", category: "cargo", tier: tier.SILVER, icon: "Package",
    en: { title: "Freight Pro", desc: "Haul 100 tonnes of cargo." },
    de: { title: "Fracht-Profi", desc: "100 Tonnen Fracht befördert." },
    check: (ctx) => (c(ctx).totalCargoKg || 0) >= 100000 },
  { id: "cargo_1000t", category: "cargo", tier: tier.GOLD, icon: "Package",
    en: { title: "Heavy Hauler", desc: "Haul 1,000 tonnes of cargo." },
    de: { title: "Schwerlast-Transporter", desc: "1.000 Tonnen Fracht befördert." },
    check: (ctx) => (c(ctx).totalCargoKg || 0) >= 1000000 },
  { id: "cargo_10kt", category: "cargo", tier: tier.PLATINUM, icon: "Package",
    en: { title: "Logistics Empire", desc: "Haul 10,000 tonnes of cargo." },
    de: { title: "Logistik-Imperium", desc: "10.000 Tonnen Fracht befördert." },
    check: (ctx) => (c(ctx).totalCargoKg || 0) >= 10000000 },

  // --- Aircraft variety (57-66) ---
  { id: "fly_prop", category: "variety", tier: tier.BRONZE, icon: "Plane",
    en: { title: "Prop Pilot", desc: "Complete a flight in a small prop." },
    de: { title: "Propeller-Pilot", desc: "Flug mit einem kleinen Propellerflugzeug abschließen." },
    check: (ctx) => (c(ctx).flightsByType?.small_prop || 0) >= 1 },
  { id: "fly_turboprop", category: "variety", tier: tier.BRONZE, icon: "Wind",
    en: { title: "Turboprop Talent", desc: "Complete a flight in a turboprop." },
    de: { title: "Turboprop-Talent", desc: "Flug mit einem Turboprop abschließen." },
    check: (ctx) => (c(ctx).flightsByType?.turboprop || 0) >= 1 },
  { id: "fly_regional", category: "variety", tier: tier.BRONZE, icon: "Plane",
    en: { title: "Regional Jet Jockey", desc: "Complete a flight in a regional jet." },
    de: { title: "Regionaljet-Pilot", desc: "Flug mit einem Regionaljet abschließen." },
    check: (ctx) => (c(ctx).flightsByType?.regional_jet || 0) >= 1 },
  { id: "fly_narrow", category: "variety", tier: tier.SILVER, icon: "Plane",
    en: { title: "Narrow-Body Captain", desc: "Complete a flight in a narrow-body." },
    de: { title: "Narrowbody-Kapitän", desc: "Flug mit einem Narrowbody abschließen." },
    check: (ctx) => (c(ctx).flightsByType?.narrow_body || 0) >= 1 },
  { id: "fly_wide", category: "variety", tier: tier.GOLD, icon: "Plane",
    en: { title: "Wide-Body Commander", desc: "Complete a flight in a wide-body." },
    de: { title: "Widebody-Kommandant", desc: "Flug mit einem Widebody abschließen." },
    check: (ctx) => (c(ctx).flightsByType?.wide_body || 0) >= 1 },
  { id: "fly_cargo", category: "variety", tier: tier.SILVER, icon: "Truck",
    en: { title: "Cargo Captain", desc: "Complete a flight in a cargo aircraft." },
    de: { title: "Fracht-Kapitän", desc: "Flug mit einem Frachtflugzeug abschließen." },
    check: (ctx) => (c(ctx).flightsByType?.cargo || 0) >= 1 },
  { id: "all_types", category: "variety", tier: tier.PLATINUM, icon: "Grid3x3",
    en: { title: "Jack of All Wings", desc: "Fly all six aircraft categories." },
    de: { title: "Alleskönner", desc: "Alle sechs Flugzeugkategorien geflogen." },
    check: (ctx) => {
      const f = c(ctx).flightsByType || {};
      return ["small_prop","turboprop","regional_jet","narrow_body","wide_body","cargo"].every(k => (f[k] || 0) >= 1);
    } },
  { id: "airports_10", category: "variety", tier: tier.BRONZE, icon: "MapPin",
    en: { title: "Touring", desc: "Visit 10 unique airports." },
    de: { title: "Unterwegs", desc: "10 verschiedene Flughäfen besucht." },
    check: (ctx) => (c(ctx).uniqueAirports?.size || 0) >= 10 },
  { id: "airports_50", category: "variety", tier: tier.SILVER, icon: "MapPin",
    en: { title: "Well Traveled", desc: "Visit 50 unique airports." },
    de: { title: "Vielgereist", desc: "50 verschiedene Flughäfen besucht." },
    check: (ctx) => (c(ctx).uniqueAirports?.size || 0) >= 50 },
  { id: "airports_100", category: "variety", tier: tier.GOLD, icon: "Globe",
    en: { title: "Globetrotter", desc: "Visit 100 unique airports." },
    de: { title: "Globetrotter", desc: "100 verschiedene Flughäfen besucht." },
    check: (ctx) => (c(ctx).uniqueAirports?.size || 0) >= 100 },

  // --- Financial (67-76) ---
  { id: "first_profit", category: "finance", tier: tier.BRONZE, icon: "DollarSign",
    en: { title: "First Profit", desc: "Make your first profitable flight." },
    de: { title: "Erster Gewinn", desc: "Ersten profitablen Flug abschließen." },
    check: (ctx) => ctx.flights.some(f => (f.profit || 0) > 0) },
  { id: "profit_100k", category: "finance", tier: tier.BRONZE, icon: "DollarSign",
    en: { title: "Six Figures", desc: "Earn $100,000 total profit." },
    de: { title: "Sechsstellig", desc: "$100.000 Gesamtgewinn erzielen." },
    check: (ctx) => (c(ctx).totalProfit || 0) >= 100000 },
  { id: "profit_1m", category: "finance", tier: tier.SILVER, icon: "DollarSign",
    en: { title: "Millionaire", desc: "Earn $1M total profit." },
    de: { title: "Millionär", desc: "$1 Mio. Gesamtgewinn erzielen." },
    check: (ctx) => (c(ctx).totalProfit || 0) >= 1000000 },
  { id: "profit_10m", category: "finance", tier: tier.GOLD, icon: "DollarSign",
    en: { title: "Ten Million Club", desc: "Earn $10M total profit." },
    de: { title: "Zehn-Millionen-Club", desc: "$10 Mio. Gesamtgewinn erzielen." },
    check: (ctx) => (c(ctx).totalProfit || 0) >= 10000000 },
  { id: "profit_100m", category: "finance", tier: tier.PLATINUM, icon: "Coins",
    en: { title: "Aviation Mogul", desc: "Earn $100M total profit." },
    de: { title: "Luftfahrt-Mogul", desc: "$100 Mio. Gesamtgewinn erzielen." },
    check: (ctx) => (c(ctx).totalProfit || 0) >= 100000000 },
  { id: "balance_1m", category: "finance", tier: tier.SILVER, icon: "Wallet",
    en: { title: "Cash Rich", desc: "Hold $1M in balance." },
    de: { title: "Finanzstark", desc: "$1 Mio. Kontostand erreichen." },
    check: (ctx) => (c(ctx).currentBalance || 0) >= 1000000 },
  { id: "balance_10m", category: "finance", tier: tier.GOLD, icon: "Wallet",
    en: { title: "Corporate Giant", desc: "Hold $10M in balance." },
    de: { title: "Konzern-Gigant", desc: "$10 Mio. Kontostand erreichen." },
    check: (ctx) => (c(ctx).currentBalance || 0) >= 10000000 },
  { id: "single_profit_100k", category: "finance", tier: tier.SILVER, icon: "TrendingUp",
    en: { title: "Big Ticket", desc: "Single flight profit over $100k." },
    de: { title: "Großer Auftrag", desc: "Einzelflug-Gewinn über $100.000." },
    check: (ctx) => ctx.flights.some(f => (f.profit || 0) >= 100000) },
  { id: "single_profit_500k", category: "finance", tier: tier.GOLD, icon: "Banknote",
    en: { title: "Jackpot Flight", desc: "Single flight profit over $500k." },
    de: { title: "Jackpot-Flug", desc: "Einzelflug-Gewinn über $500.000." },
    check: (ctx) => ctx.flights.some(f => (f.profit || 0) >= 500000) },
  { id: "fleet_value_50m", category: "finance", tier: tier.PLATINUM, icon: "Building2",
    en: { title: "Fleet Empire", desc: "Fleet value over $50M." },
    de: { title: "Flotten-Imperium", desc: "Flottenwert über $50 Mio." },
    check: (ctx) => (c(ctx).fleetValue || 0) >= 50000000 },

  // --- Company / Level (77-84) ---
  { id: "level_5", category: "career", tier: tier.BRONZE, icon: "Award",
    en: { title: "Climbing Ranks", desc: "Reach company level 5." },
    de: { title: "Aufsteiger", desc: "Firmenlevel 5 erreichen." },
    check: (ctx) => (c(ctx).currentCompanyLevel || 1) >= 5 },
  { id: "level_10", category: "career", tier: tier.SILVER, icon: "Award",
    en: { title: "Double Digits", desc: "Reach company level 10." },
    de: { title: "Zweistellig", desc: "Firmenlevel 10 erreichen." },
    check: (ctx) => (c(ctx).currentCompanyLevel || 1) >= 10 },
  { id: "level_25", category: "career", tier: tier.GOLD, icon: "Medal",
    en: { title: "Industry Pro", desc: "Reach company level 25." },
    de: { title: "Branchen-Profi", desc: "Firmenlevel 25 erreichen." },
    check: (ctx) => (c(ctx).currentCompanyLevel || 1) >= 25 },
  { id: "level_50", category: "career", tier: tier.PLATINUM, icon: "Crown",
    en: { title: "Industry Legend", desc: "Reach company level 50." },
    de: { title: "Branchen-Legende", desc: "Firmenlevel 50 erreichen." },
    check: (ctx) => (c(ctx).currentCompanyLevel || 1) >= 50 },
  { id: "rep_75", category: "career", tier: tier.SILVER, icon: "ThumbsUp",
    en: { title: "Trusted Brand", desc: "Reach 75 reputation." },
    de: { title: "Vertrauensmarke", desc: "75 Reputation erreichen." },
    check: (ctx) => (c(ctx).currentReputation || 0) >= 75 },
  { id: "rep_90", category: "career", tier: tier.GOLD, icon: "Heart",
    en: { title: "Beloved Airline", desc: "Reach 90 reputation." },
    de: { title: "Beliebte Airline", desc: "90 Reputation erreichen." },
    check: (ctx) => (c(ctx).currentReputation || 0) >= 90 },
  { id: "fleet_5", category: "career", tier: tier.BRONZE, icon: "Plane",
    en: { title: "Small Fleet", desc: "Own 5 aircraft." },
    de: { title: "Kleine Flotte", desc: "5 Flugzeuge besitzen." },
    check: (ctx) => (c(ctx).fleetSize || 0) >= 5 },
  { id: "fleet_20", category: "career", tier: tier.GOLD, icon: "Plane",
    en: { title: "Major Operator", desc: "Own 20 aircraft." },
    de: { title: "Großer Betreiber", desc: "20 Flugzeuge besitzen." },
    check: (ctx) => (c(ctx).fleetSize || 0) >= 20 },

  // --- Safety / No-incidents (85-92) ---
  { id: "safe_10", category: "safety", tier: tier.BRONZE, icon: "ShieldCheck",
    en: { title: "Safe Operator", desc: "10 flights without any incident." },
    de: { title: "Sicherer Betreiber", desc: "10 Flüge ohne Zwischenfälle." },
    check: (ctx) => (c(ctx).noIncidentStreak || 0) >= 10 },
  { id: "safe_50", category: "safety", tier: tier.SILVER, icon: "ShieldCheck",
    en: { title: "Incident-Free", desc: "50 flights without any incident." },
    de: { title: "Zwischenfallfrei", desc: "50 Flüge ohne Zwischenfälle." },
    check: (ctx) => (c(ctx).noIncidentStreak || 0) >= 50 },
  { id: "safe_200", category: "safety", tier: tier.PLATINUM, icon: "Shield",
    en: { title: "Safety Champion", desc: "200 flights without any incident." },
    de: { title: "Sicherheits-Champion", desc: "200 Flüge ohne Zwischenfälle." },
    check: (ctx) => (c(ctx).noIncidentStreak || 0) >= 200 },
  { id: "no_crash_100", category: "safety", tier: tier.GOLD, icon: "Heart",
    en: { title: "Survivor", desc: "100 flights without a crash." },
    de: { title: "Überlebenskünstler", desc: "100 Flüge ohne Absturz." },
    check: (ctx) => (c(ctx).completedFlights || 0) >= 100 && (c(ctx).crashCount || 0) === 0 },
  { id: "fuel_efficient", category: "safety", tier: tier.SILVER, icon: "Leaf",
    en: { title: "Fuel Saver", desc: "Complete 10 flights with score 90+." },
    de: { title: "Sparbrötchen", desc: "10 Flüge mit Score 90+ abschließen." },
    check: (ctx) => (c(ctx).highScoreFlights || 0) >= 10 },
  { id: "no_overstress", category: "safety", tier: tier.GOLD, icon: "Shield",
    en: { title: "Smooth Operator", desc: "50 flights without overstress event." },
    de: { title: "Feinfühlig", desc: "50 Flüge ohne Überlastung." },
    check: (ctx) => (c(ctx).completedFlights || 0) >= 50 && (c(ctx).overstressCount || 0) === 0 },
  { id: "no_stall", category: "safety", tier: tier.SILVER, icon: "Waves",
    en: { title: "Aerodynamic", desc: "100 flights without a stall." },
    de: { title: "Aerodynamisch", desc: "100 Flüge ohne Strömungsabriss." },
    check: (ctx) => (c(ctx).completedFlights || 0) >= 100 && (c(ctx).stallCount || 0) === 0 },
  { id: "clean_week", category: "safety", tier: tier.SILVER, icon: "Calendar",
    en: { title: "Clean Streak", desc: "25 consecutive flights with score 85+." },
    de: { title: "Saubere Serie", desc: "25 Flüge in Folge mit Score 85+." },
    check: (ctx) => (c(ctx).bestGoodScoreStreak || 0) >= 25 },

  // --- Special / Fun (93-100) ---
  { id: "night_owl", category: "special", tier: tier.BRONZE, icon: "Moon",
    en: { title: "Night Owl", desc: "Complete a night flight (departure 22:00–04:00)." },
    de: { title: "Nachteule", desc: "Nachtflug abschließen (Start 22:00–04:00)." },
    check: (ctx) => (c(ctx).nightFlights || 0) >= 1 },
  { id: "night_owl_25", category: "special", tier: tier.GOLD, icon: "Moon",
    en: { title: "Red-Eye Regular", desc: "25 night flights." },
    de: { title: "Nachtflug-Stammgast", desc: "25 Nachtflüge." },
    check: (ctx) => (c(ctx).nightFlights || 0) >= 25 },
  { id: "early_bird", category: "special", tier: tier.SILVER, icon: "Sunrise",
    en: { title: "Early Bird", desc: "10 flights departing before 07:00." },
    de: { title: "Frühaufsteher", desc: "10 Flüge mit Start vor 07:00." },
    check: (ctx) => (c(ctx).earlyFlights || 0) >= 10 },
  { id: "same_day_3", category: "special", tier: tier.SILVER, icon: "Repeat",
    en: { title: "Triple Shift", desc: "Complete 3 flights in one calendar day." },
    de: { title: "Dreifach-Schicht", desc: "3 Flüge an einem Tag abschließen." },
    check: (ctx) => (c(ctx).maxFlightsInOneDay || 0) >= 3 },
  { id: "same_day_5", category: "special", tier: tier.GOLD, icon: "Zap",
    en: { title: "Iron Pilot", desc: "5 flights in one calendar day." },
    de: { title: "Eiserner Pilot", desc: "5 Flüge an einem Tag abschließen." },
    check: (ctx) => (c(ctx).maxFlightsInOneDay || 0) >= 5 },
  { id: "perfect_score_butter", category: "special", tier: tier.PLATINUM, icon: "Crown",
    en: { title: "Flawless Flight", desc: "Score 99+ with a butter landing." },
    de: { title: "Makelloser Flug", desc: "Score 99+ mit Butter-Landung." },
    check: (ctx) => ctx.flights.some(f => {
      const score = f.flight_score || f.xplane_data?.final_score || 0;
      const vs = Math.abs(f.xplane_data?.touchdown_vspeed || 0);
      return score >= 99 && vs > 0 && vs < 100;
    }) },
  { id: "comeback", category: "special", tier: tier.GOLD, icon: "RotateCcw",
    en: { title: "Comeback Kid", desc: "After a failed flight, score 95+ on the next." },
    de: { title: "Comeback", desc: "Nach fehlgeschlagenem Flug direkt Score 95+." },
    check: (ctx) => (c(ctx).comebackCount || 0) >= 1 },
  { id: "collector", category: "special", tier: tier.PLATINUM, icon: "Trophy",
    en: { title: "Achievement Hunter", desc: "Unlock 75 other achievements." },
    de: { title: "Achievement-Jäger", desc: "75 andere Achievements freischalten." },
    check: (ctx) => (c(ctx).unlockedCountExcludingSelf || 0) >= 75 },
];

export const ACHIEVEMENT_CATEGORIES = [
  { id: "landing", en: "Landing", de: "Landung" },
  { id: "precision", en: "Precision", de: "Präzision" },
  { id: "score", en: "Score", de: "Bewertung" },
  { id: "milestone", en: "Milestones", de: "Meilensteine" },
  { id: "distance", en: "Distance", de: "Distanz" },
  { id: "passengers", en: "Passengers", de: "Passagiere" },
  { id: "cargo", en: "Cargo", de: "Fracht" },
  { id: "variety", en: "Variety", de: "Vielfalt" },
  { id: "finance", en: "Finance", de: "Finanzen" },
  { id: "career", en: "Career", de: "Karriere" },
  { id: "safety", en: "Safety", de: "Sicherheit" },
  { id: "special", en: "Special", de: "Spezial" },
];

export const TIER_STYLES = {
  bronze: {
    border: "border-amber-700/50",
    bg: "from-amber-900/40 to-amber-950/40",
    text: "text-amber-400",
    glow: "shadow-[0_0_12px_rgba(180,83,9,0.25)]",
    label: { en: "Bronze", de: "Bronze" },
  },
  silver: {
    border: "border-slate-400/40",
    bg: "from-slate-700/40 to-slate-900/40",
    text: "text-slate-300",
    glow: "shadow-[0_0_14px_rgba(148,163,184,0.25)]",
    label: { en: "Silver", de: "Silber" },
  },
  gold: {
    border: "border-amber-400/50",
    bg: "from-amber-600/30 to-yellow-900/40",
    text: "text-amber-300",
    glow: "shadow-[0_0_16px_rgba(251,191,36,0.35)]",
    label: { en: "Gold", de: "Gold" },
  },
  platinum: {
    border: "border-cyan-300/50",
    bg: "from-cyan-700/30 to-fuchsia-900/40",
    text: "text-cyan-200",
    glow: "shadow-[0_0_20px_rgba(103,232,249,0.45)]",
    label: { en: "Platinum", de: "Platin" },
  },
};